name: If Condition Demo
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: using if first time 
        if: github.ref_name == 'main'
        run: echo "This is sample usage of the if condition"
              
